package com.rizqi.lumecolorsapp.model

class MOpname(
    var id : String = "",
    var id_produk : String = "",
    var id_user : String = "",
    var id_gudang : String = "",
    var kode_produk : String = "",
    var nama_produk : String = "",
    var id_kategori : String = "",
    var satuan : String = "",
    var deskripsi : String = "",
    var hpp : String = "",
    var harga_jual : String = "",
    var coa_persediaan : String = "",
    var coa_hpp : String = "",
    var coa_pendapatan : String = "",
    var gambar : String = "",
    var qr_size : String = "",
    var qr_code : String = "",
    var valid : String = "",
    var insert_by : String = "",
    var nama_kategori : String = "",
    var qty : String = "",
    var saldo_awal : String = "",
    var periode : String = "",
)