package com.rizqi.lumecolorsapp.model

class MStok(
    var id : String = "",
    var ref : String = "",
    var no_ref : String = "",
    var tipe : String = "",
    var id_produk : String = "",
    var qty : String = "",
    var tgl : String = "",
    var periode : String = "",
    var ket : String = "",
    var insert_by : String = "",
    var insert_dt : String = "",
    var approve_by : String = "",
    var approve_dt: String = "",
    var kode_produk : String = "",
    var nama_produk : String = "",
    var gambar : String = "",
    var no_delivery : String = "",
    var no_batch : String = "",
    var exp_date : String = "",
    var qty_lolos : String = "",
    var qty_reject : String = "",
    var status : String = "",
    var qrcode : String = "",
)